apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-gateway
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:Ehroen/llm-inference-platform.git
    targetRevision: main
    path: apps/fastapi-gateway/chart
    helm:
      releaseName: fastapi-gateway

  destination:
    server: https://kubernetes.default.svc
    namespace: llm

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
